##########################################################################
# ph0llux:42330a584fde2068cb3217b0f33d5f3255e19e63ecc2ee397317aa534a33900a
##########################################################################
[alias]     # command aliases
b = "build"
c = "check"
t = "test"
r = "run"
rr = "run --release"

[build]
target-dir = "/tmp/cargo/targets"	# path of where to place all generated artifacts