##########################################################################
# ph0llux:e15448a1b93e05c4329d251792735b07801d1961e0ace5c1f8c1c84e0dea97b6
##########################################################################
[general]
author = "ph0llux" #name of the author (mostly used: nicknames or firstnames)
email = "ph0llux@pm.me" #your email address (will be configured globally)
sign_key = "your_key" #could be any string value (utf8 conform)

[syntax_c]
file_extensions = [ "rs", "cpp", "js", "c", "go" ] #source code file extensions with c syntax style comments (e.g. "//", or "/*****/")

[syntax_hashtag]
file_extensions = [ "sh", "toml", "py" ] #source code file extensions with bash-script syntax style comments (e.g. "#")